CREATE TABLE "mifid" (
	"id" text PRIMARY KEY NOT NULL,
	"client_id" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"address" text NOT NULL,
	"phone" text NOT NULL,
	"birth_date" text NOT NULL,
	"marital_status" text NOT NULL,
	"employment_status" text NOT NULL,
	"education_level" text NOT NULL,
	"annual_income" integer NOT NULL,
	"monthly_expenses" integer NOT NULL,
	"debts" integer NOT NULL,
	"dependents" integer NOT NULL,
	"assets" jsonb NOT NULL,
	"investment_horizon" text NOT NULL,
	"retirement_interest" integer NOT NULL,
	"wealth_growth_interest" integer NOT NULL,
	"income_generation_interest" integer NOT NULL,
	"capital_preservation_interest" integer NOT NULL,
	"estate_planning_interest" integer NOT NULL,
	"investment_experience" text NOT NULL,
	"past_investment_experience" jsonb NOT NULL,
	"financial_education" jsonb NOT NULL,
	"risk_profile" text NOT NULL,
	"portfolio_drop_reaction" text NOT NULL,
	"volatility_tolerance" text NOT NULL,
	"years_of_experience" text NOT NULL,
	"investment_frequency" text NOT NULL,
	"advisor_usage" text NOT NULL,
	"monitoring_time" text NOT NULL,
	"specific_questions" text
);
--> statement-breakpoint
ALTER TABLE "mifid" ADD CONSTRAINT "mifid_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;